In [5]:
import pandas as pd
import numpy as np
import nltk

In [6]:
nltk.download('gutenberg')

from nltk.corpus import gutenberg

df = gutenberg.raw('shakespeare-hamlet.txt')

with open('hamlet.txt','w') as file:
  file.write(df)

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [7]:
## Data processing
!pip install tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

#load the dataset
with open('hamlet.txt','r') as file:
  text = file.read().lower()

##Tokenize the text - indexing for words
tokens = Tokenizer()
tokens.fit_on_texts([text])
total_words = len(tokens.word_index)+1
total_words


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 644.9/644.9 MB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 84.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 108.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 87.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 115.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 15.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 5.6 MB/s eta 0:00:00


4818

In [8]:

tokens.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

In [9]:
#Create Input Sequences

input_sequences = []
for line in text.split('\n'):
  token_list = tokens.texts_to_sequences([line])[0]
  for i in range(1,len(token_list)):
    n_gram_sequence = token_list[:i+1]
    input_sequences.append(n_gram_sequence)

In [10]:
## pad Sequencing

max_sequence_len = max([len(x) for x in input_sequences])
input_sequences = np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]], dtype=int32)

In [11]:
##Create Predictors and label

import tensorflow as tf
x,y = input_sequences[:,:-1],input_sequences[:,-1]


In [12]:
y

array([ 687,    4,   45, ..., 1047,    4,  193], dtype=int32)

In [13]:
y= tf.keras.utils.to_categorical(y,num_classes = total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
#split the data
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
#Train our LSTM RNN

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout

#Definition of model
model = Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(LSTM(150,return_sequences = True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation='softmax'))

#Compile the model
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
##Train the model
history = model.fit(x_train,y_train,epochs = 150,validation_data=(x_test,y_test),verbose=1)

Epoch 1/150
644/644 ━━━━━━━━━━━━━━━━━━━━ 38s 53ms/step - accuracy: 0.0304 - loss: 7.1538 - val_accuracy: 0.0336 - val_loss: 6.6938
Epoch 2/150
644/644 ━━━━━━━━━━━━━━━━━━━━ 32s 49ms/step - accuracy: 0.0360 - loss: 6.4551 - val_accuracy: 0.0416 - val_loss: 6.7633
Epoch 3/150
644/644 ━━━━━━━━━━━━━━━━━━━━ 31s 48ms/step - accuracy: 0.0430 - loss: 6.3156 - val_accuracy: 0.0455 - val_loss: 6.7964
Epoch 4/150
644/644 ━━━━━━━━━━━━━━━━━━━━ 32s 49ms/step - accuracy: 0.0500 - loss: 6.2261 - val_accuracy: 0.0492 - val_loss: 6.8043
Epoch 5/150
644/644 ━━━━━━━━━━━━━━━━━━━━ 32s 49ms/step - accuracy: 0.0541 - loss: 6.0534 - val_accuracy: 0.0579 - val_loss: 6.8219
Epoch 6/150
644/644 ━━━━━━━━━━━━━━━━━━━━ 31s 49ms/step - accuracy: 0.0595 - loss: 5.8990 - val_accuracy: 0.0641 - val_loss: 6.8748
Epoch 7/150
644/644 ━━━━━━━━━━━━━━━━━━━━ 31s 49ms/step - accuracy: 0.0658 - loss: 5.7729 - val_accuracy: 0.0649 - val_loss: 6.9380
Epoch 8/150
644/644 ━━━━━━━━━━━━━━━━━━━━ 32s 50ms/step - accuracy: 0.0727 - loss: 5

In [17]:
# Function to predict the next word
def predict_next_word(model, tokens, text, max_sequence_len):
    token_list = tokens.texts_to_sequences([text])[0]
    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len-1):]  # Ensure the sequence length matches max_sequence_len-1
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=1)
    for word, index in tokens.word_index.items():
        if index == predicted_word_index:
            return word
    return None

In [18]:
input_text="To be or not to be"
print(f"Input text:{input_text}")
max_sequence_len = model.input_shape[1]+1
next_word=predict_next_word(model,tokens,input_text,max_sequence_len)
print(f"Next Word PRediction:{next_word}")

Input text:To be or not to be
Next Word PRediction:that


In [20]:
## Save the model
model.save("next_word_lstm.h5")
## Save the tokenizer
import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokens,handle,protocol=pickle.HIGHEST_PROTOCOL)

In [22]:
input_text="  Barn. Last night of all,When yond same"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokens,input_text,max_sequence_len)
print(f"Next Word Prediction:{next_word}")

Input text:  Barn. Last night of all,When yond same
Next Word Prediction:eyes
